version: "3.8"

services:
  # Juice Shop instances
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    hostname: juice-shop
    networks:
      - juice-shop-net
    expose:
      - 3000

  # Vulnerable App instances (now using your Docker Hub image)
  vulnerable-app:
    image: lekski/ssd_petproject:latest
    container_name: vulnerable-app
    hostname: vulnerable-app
    expose:
      - 8000

  # Nginx load balancers
  juice-shop-nginx:
    image: nginx:alpine
    container_name: juice-shop-balancer
    ports:
      - 3000:3000
    volumes:
      - ./nginx/juice-shop.conf:/etc/nginx/nginx.conf
    depends_on:
      - juice-shop
    networks:
      - juice-shop-net

  vulnerable-app-nginx:
    image: nginx:alpine
    container_name: vulnerable-app-balancer
    ports:
      - 8000:8000
    volumes:
      - ./nginx/vulnerable-app.conf:/etc/nginx/nginx.conf
    depends_on:
      - vulnerable-app

networks:
  juice-shop-net:
